# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c9d3fa9f0eb27b3edae67b82eeb50d32edb3832d4a55bf9de73aabfd74c978d99d5cd4a3f8952b3bf3e84dfa50780c8001568899bb064640f85df8e469b374d

test:
  secret_key_base: 616c63ed9756eb1c41388853294f1059e18377d3b8e23841a22f5c0feb0d09448d06106116686f8be05434bf4628fe2b3ac553bb59a94671ff3e5a4a65471939

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
